name: dooble_quest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  sensors_plus: ^6.0.0
  audioplayers: ^6.5.1
  noise_meter: ^5.1.0
  permission_handler: ^12.0.1
  nearby_connections: ^4.3.0
  web_socket_channel: ^2.4.0
  intl: ^0.20.2
  socket_io_client: ^2.0.3+1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_pose_detection: ^0.14.0
  camera: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: BarlowR
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
    - family: BarlowB
      fonts:
        - asset: assets/fonts/Barlow-Bold.ttf
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf

  assets:
    - assets/img/TireCowBoy.png
    - assets/img/CamilleKaze.png
    - assets/img/FlashMcClou.png
    - assets/img/Extincteur.png
    - assets/img/SquatMiner.png
    - assets/img/RockyBalBoBo.png
    - assets/sfx/explosion.mp3
    - assets/sfx/tick.mp3
    - assets/sfx/coin.mp3
    - assets/sfx/coup_de_poing.mp3
    - assets/sfx/gun_shoot.mp3
    - assets/img/game/bombe.png
    - assets/img/game/explosion.png
    - assets/img/game/cowboy_bg.png
    - assets/img/game/cowboy_gun.png
    - assets/img/game/feu.png
    - assets/img/game/vent.png
    - assets/img/game/gemme.png
    - assets/img/game/fond_mine.png
    - assets/img/game/gant.png
    - assets/img/game/ring.png

  uses-material-design: true
